; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_protocol = teensy-gui
; Set your Teensy's COM port (e.g., COM3, COM4)
upload_port = COM6
; build_flags = -Wall -Wextra -O2
# Temporary: enable ASCII Teleplot/debug prints during diagnosis
build_flags = -DTELEMETRY_ALLOW_ASCII_TELEPLOT=1
debug_tool = jlink
debug_init_break = tbreak setup
lib_deps = 
	adafruit/Adafruit BusIO@^1.14.5
	arkhipenko/TaskScheduler@^3.7.0
	adafruit/Adafruit Unified Sensor@^1.1.14
	mbed-mkanli/MaxSonar
	adafruit/Adafruit TCS34725@^1.4.3


